### ISSUE TITLE
Can we start using it in production?

### ISSUE THREAD

**Issue by afidegnum** [flexxui/flexx#242]
Hi, 

what's the status of this project? can we start to use it in production?

**Comment by almarklein** [comment]
It's still in an "alpha" status. Things are pretty stable, runtime-wise, but we're still making significant changes, including those that change the API, and we cannot promise to keep things backward compatible at this point.

So, if you have an interest in using it, trying it out and reporting issues (from bugs to usability issues) is helpful. Whether you use it in production is up to you, but be aware that things might break and need changes when you update Flexx.

**Comment by afidegnum** [comment]
What's the milestore? what needs improving so if possible, i can contribute? how can this be integrate to other frameworks like flask, etc... ?

**Comment by almarklein** [comment]
We don't have a 1.0 milestone yet. But with each release we should be closer to stable-ness.

Here are some issues that I think are important missing parts, or can potentially introduce API changes:

* There might be some API changes related to mouse/pointer events #149
* PyScript performance should be improved (at least allow it to run real fast), probably no API changes though #104 
* We've seen Flexx to not work on Chrome in certain cases because we use `eval` #65
* At the moment the support for the notebook is rather unstable.
* If you need to send (large) data to the client, that's still something we need to figure out #143
* We don't have an awful lot of widgets yet. We basically add them when needed. #111 
* Better debugging support on the JS side. #179

> how can this be integrate to other frameworks like flask, etc... ?

Flexx runs on Tornado, so I suppose you'd do it in a similar way as integrating Tornado with flask. Though if you have a choice, the easiest approach might be to just use Tornado.

**Comment by almarklein** [comment]
Small update: Flexx should get beta status with v0.6, though I'll try to get most things that cause severe backwards incompatibilities in v.0.5. With beta I mean we take better care of backwards incompatibilities and deprecation paths.

**Comment by afidegnum** [comment]
sure, still watching the update, i m very interested in it,

**Comment by afidegnum** [comment]
have you think of blending or adding ELM ?

**Comment by almarklein** [comment]
> have you think of blending or adding ELM

No. Are you suggesting to transpile Python to Elm and then to JS? What would the advantage be?

Actually, TypeScript might be a better target in that case, I guess. Though when WebAssembly becomes available, I could see us target that.

**Comment by afidegnum** [comment]
no, rather Elm to Js

**Comment by almarklein** [comment]
But there is hardly any JS in Flexx. Everything is transpiled from Python :)

**Comment by almarklein** [comment]
Closing this. Flexx is nearing a release that brings it to Beta status. Not quite "production ready", but a step closer to it.
