### ISSUE TITLE
Tree item in JS

### ISSUE THREAD

**Issue by Maxyme** [flexxui/flexx#301]
The TreeWidget should be able to take in dicts are input items rather than only treeitem models. This would allow dynamically populating the TreeWidget from Js.

**Comment by almarklein** [comment]
I think allowing both dicts and treeitem models would be confusing and hard to maintain.  For reference the items in a ComboBox are just strings. I think the main question is whether we can implement an effective TreeWidget (i.e. come up with a good API on the widget itself) without its items being models.

Reasons why we would want this are that we can currently only add items from Python, and that very large or dynamic lists may become "heavy".

**Comment by almarklein** [comment]
Do you mean you'd like the dicts have methods? I don't think that will work well, e.g. they won't be models, so you wont be able to connect to them.

If a TreeWidget would have dicts as items, they should be just dicts, I think, and all the API would come on the TreeWidget itself. Let's try to see what that would look like:

```py
tree = TreeWidget(items=[...])
# For booleans it works pretty ok
tree.checked  #-> list of items that are checked
tree.selected  #-> similar
tree.visible  #-> list of items, mmm, not very nice, but ok
tree.text  # -> ???
tree.get_text(100)  # get text of 100th item
tree.set_text(100, 'foo')  # I thought we liked properties?
```

After thinking this true I think we should stick to models. It is even more effective in a way if a tree changes a lot, since the list of items is just references instead of dicts with multiple attributes.

Back to the original problem. One solution would be to allow creating model objects from JS under specific situations (for specific classes?). This needs a lot of thought though. I am not eager.

Another option could be to think about a new widget (`ListWidget`?) that is similar to a combobox except its a list; items are just strings and the user can select one or more of them. Than you can get away with a simple API:
```py
list1 = ListWidget(items=[...])
list1.items = [...]
list1.selected  # -> list of indices or list of strings
```

**Comment by almarklein** [comment]
TreeItems are now Widgets, which are JsComponents, and thus can be instantiated in JS.
