### ISSUE TITLE
Motivation and differences versus Bokeh arquitecture

### ISSUE THREAD

**Issue by double-thinker** [flexxui/flexx#336]
Hi. This is not a issue exactly, it's a question or discussion.

I use to work with Bokeh for fast prototyping of data-related apps in Python and other similar frameworks (e.g. ipywidgets) and now I'm experimenting with flexx with bokeh/image-based plots.

I love some features of flexx and your approach 👍  Thanks for your work but I'm curious about what are the motivation behind developing this framework instead extend others (I'm thinking about Bokeh).

You'd forgot about sync client-server logic if you use model's logic of Bokeh and its server. Less work and more syneric. Wouldn't?

And related, What are main differences between both architectures? For example, I saw (but only after a fast reading of your docs) that flexx "only" uses one server (App) instead of have a central one (bokeh-server) that communicates with one or more "app-servers".

**Comment by almarklein** [comment]
Interesting questions!

As you know, one central idea of Flexx is writing classes that define both the Python and JS behavior, and automatically sync properties and communicate events. This needs a tight coupling. Also Flexx needs to somehow serve dynamically created javascript to the client (which is now actually done by pushing such assets over the websocket). Because of these specific needs, I don't think there is much that we could use from Bokeh's server. Though we use Tornado though (like Bokeh does), which takes care of a lot.

I don't know the Bokeh server *that* well, but as you said, one main difference is that Bokeh uses a cental server, and you spawn one app per process, while Flexx has the server in the process that spawns an app, but each process can serve multiple apps.

**Comment by hieu-n** [comment]
Hi, I found this page by Google. Flexx looks interesting to me. However, a friend of mine told he built an app with `ipywidgets` + jupyter dashboard (https://github.com/jupyter/dashboards) and jupyter dashboard server (https://github.com/jupyter-incubator/dashboards_server).

I hope you guys can give some comments on how `flexx` compared to `ipywidgets` + jupyter dashboard + jupyter dashboard server.

**Comment by almarklein** [comment]
The tools that you mention are all based on the Jupyter architecture. Flexx is a single project that includes the server. I don't have any experience with these tools, but I suspect that they become less useful for more complex applications. Flexx is intended to work for small dashboard-like apps as well as larger GUI applications. (The latter could be better, and we're about to make some changes to make Flexx scale better for more complex apps #367.) 

Another thing that sets Flexx apart is the ability to define client-side code using PyScript, a subset of Python that is transpiled to JavaScript. This makes it easier for Python devs to make use of web technology, though some knowledge of JS and the DOM certainly helps.

Further, it can be used to run apps as desktop apps as well as web apps. And if your app does not actually need the server, it can be exported to standalone HTML, e.g. to include it in a blog post.

**Comment by almarklein** [comment]
Closing this. I will also add that with the latest refactoring, Flexx is now using a "modern" way to deal with events and information flow, which helps applications to stay predictable and understandable. Unlike systems that adopt a more classes MVC approach.
