### ISSUE TITLE
Version 0.4.2 not available on PyPI

### ISSUE THREAD

**Issue by frosch01** [flexxui/flexx#420]

**Comment by frosch01** [comment]
Can you please forward the latest version 0.4.2 to Python Package Index? Or is there a reason why this is not done? I tried to find out what are the changes/release notes but I was not able to find any hint in the documentation. A little hint on this would be helpful.

Thx

**Comment by almarklein** [comment]
Hi,

Yes, there is a reason why Flexx was not uploaded to Pypi. The latest "tag release" was done to mark the state of Flexx before the big refactoring that is currently taken place.

About a year ago we've realized certain limitations of Flexx that would prevent it from being useful at a large scale. Since then we've been making plans to improve Flexx to move beyond these limitations. Since these changes will also mean substantial changes in the API, we've been "silent" about Flexx lately, and this is also the reason why the latest release was not uploaded to Pypi; we are not eager for too many new users at this point ;)

The refactoring is well on its way now, and I expect things to land into master within a few weeks. I'd like to give it a few weeks to settle after that, but a proper release (also on Pypi) should not be too far away ...

**Comment by almarklein** [comment]
I've added a notice in the readme to explain the current state. I'm leaving this issue open as its a very valid question and more people might be looking for an answer.

**Comment by almarklein** [comment]
Closing; preparing for 0.5.
