### ISSUE TITLE
Is Plotwidget able to plot more than one line?

### ISSUE THREAD

**Issue by andyneer** [flexxui/flexx#421]
I was trying to plot a graph in Flexx with two lines, and I was not able to do it. 
I tried something like this:

```
a = [1,2,3,4,5]
b = [6,7,8,9,10]
p = ui.PlotWidget(xdata=[a,b], ydata=[2*a,2*b],
                  line_width=[4,4], line_color=['red','blue'])
```

I did not found any example about how to do it. I even tried BokehWidget, but it does not seem to work in Python 2.7 and 3.3 in Flexx's latest version (0.4.1).

**Comment by almarklein** [comment]
N,o the PlotWidget does not support it. It's meant as a very simple widget to make simple plots work, but beyond that we recommend Bokeh in general.

It could indeed be that the Bokeh Widget is currently broken; I have not kept it updated for a while. We're now working on a major refactoring of (nearly) the whole of Flexx. It's not unlikely that the Bokeh widget will be fixed as part of that ... (and otherwise we should do it soon after).

**Comment by almarklein** [comment]
Bokeh widget is working again, although #209 is still open
