### ISSUE TITLE
Difference between 'set' and 'replace' for in-place mutations of list props

### ISSUE THREAD

**Issue by Korijn** [flexxui/flexx#442]
From [the docs](http://flexx.readthedocs.io/en/latest/event/intro.html#mutations-to-array-like-properties):

> This allows more fine-grained control over state updates, which can also be handled by reactions in much more efficient ways. The types of mutations are ‘set’ (the default), ‘insert’, ‘replace’, and ‘remove’. In the latter, the provided value is the number of elements to remove. For the others it must be a list of elements to set/insert/replace at the specified index.

Replacing the entire list is done with the 'set' operation, which is the default. I'm including the optional kwargs anyway just so I can state my point more clearly:

`self._mutate_items(new_list, mutation='set', index=-1)`

Replacing an item is done with the operation 'replace' and an 'index':

`self._mutate_items([item], mutation='replace', index=11)`

Now I have two questions:

* Why do I have to pass a list of 1 element to replace 1 element? Why not just an element?
* Isn't 'replace' exactly the same as 'set', with the real difference being the >= 0 value of the index kwarg?

**Comment by almarklein** [comment]
> Why do I have to pass a list of 1 element to replace 1 element? Why not just an element?

Because it allows you to replace multiple successive elements at once. I've considered allowing a single element, but that gets confusing when the elements themselves are lists.

> Isn't 'replace' exactly the same as 'set', with the real difference being the >= 0 value of the index kwarg?

No. If your initial list contains 10 elements, and you `set` it using a 4-element list, the property will now have 4 elements. With `replace` it would still have 10, but with 4 elements updates.

I agree that there is room for improvement. In the docs for sure. In the API too maybe.

**Comment by Korijn** [comment]
That explains!
