### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by zappfinger** [flexxui/flexx#492]
1) How do I refresh a web page? When I use the normal refresh button for this I get a white screen with 'Starting Flexx app'. The next time I click refresh I get 'the site can't be reached' 

2) How do I trigger button B when button A is pushed? I thought
`self.B.set_checked()`
would do it, but what argument should I use? Is this the way do do it?

Richard

**Comment by almarklein** [comment]
> How do I refresh a web page? 

You can `window.location.reload()` to refresh the page from JS. You should start the server using `flx.start()` instead of `flx.run()`. These do the same thing, except that the latter stops the server when de last session is closed.

> How do I trigger button B when button A is pushed? 

If this is a `CheckBox` or `ToggleButton` then `b.set_checked(a.checked)` should work.
