### ISSUE TITLE
FYI: What I like and what I struggled with about flexx

### ISSUE THREAD

**Issue by edreamleo** [flexxui/flexx#516]
In the [Contributing to Flexx](https://flexx.readthedocs.io/en/stable/contributing.html) page Almar says, "it’s very useful to hear what you like and what you struggle with."

[This long post on leo-editor](https://groups.google.com/d/msg/leo-editor/iiZHYyLt5Po/1rnSkxPtBQAJ) discusses both topics.  I would appreciate any comments or corrections.

To summarize: flexx and pscript are works of genius. Learning flexx and pscript took a reasonable amount of time and effort.  Many thanks, Almar, for all your great work.

**Comment by edreamleo** [comment]
Feel free to leave open or close as you like.

**Comment by almarklein** [comment]
Thanks! This is very helpful. I put quite a bit of effort in the guide, but I'm way to biased to not miss important details :)

I've tried to distill things down to some possible improvements to the guide/docs:

* Make it more clear that PyComponents are not JS.
* When does the compiling happen?
* The docs on the root component are easy to "read over" at first, yet its important.
* Perhaps a separate section about init methods would be helpful.

Let me know if there's anything else!

**Comment by almarklein** [comment]
Also thanks for [The hard is what makes it great](https://www.youtube.com/watch?v=ndL7y0MIRE4) ...

**Comment by edreamleo** [comment]
On Fri, Nov 9, 2018 at 2:48 AM Almar Klein <notifications@github.com> wrote:

> Thanks! This is very helpful. I put quite a bit of effort in the guide,
> but I'm way to biased to not miss important details :)
>
> I've tried to distill things down to some possible improvements to the
> guide/docs:
>
>    - Make it more clear that PyComponents are not JS.
>    - When does the compiling happen?
>    - The docs on the root component are easy to "read over" at first, yet
>    its important.
>    - Perhaps a separate section about init methods would be helpful.
>
> Let me know if there's anything else!
>
I think the list above covers everything.

Edward

**Comment by edreamleo** [comment]
On Fri, Nov 9, 2018 at 3:03 AM Almar Klein <notifications@github.com> wrote:

> Also thanks for The hard is what makes it great
> <https://www.youtube.com/watch?v=ndL7y0MIRE4> ...
>
Hehe.  You're welcome.

Edward

**Comment by kim0** [comment]
flexx is really quite a genius piece of work! I'm in no way a python old-hand, but the flex code does so much and yet is so simple, it's just amazing. This is my first day with flexx and since I'm struggling a bit too, I figured this would be a good place to post!

* When to use PyComponent, vs just Component, vs JsComponent ..etc. Perhaps a clear table explaining use X when you want to achieve Y. You will be able to do A but won't be able to do B.
* I think I need a clear explanation of how to call the python side from a widget, and vice versa. I've read the guide on actions/emitters..etc. While it all looks very simple and elegant, I find myself still a bit confused what exactly is happening. What is the best practice, and how do I do X (usually call some side from the other)
* I now understand `PyComponents` are not JS. Alright, that makes sense. I'm now imagining some python code running on a server. But when reading the [monitor.py](https://flexx.readthedocs.io/en/stable/examples/monitor_src.html#monitor-py) example, I find that the Monitor PyComponent is building html strings and a UI. How/Why is that so

**Comment by almarklein** [comment]
Thanks for your comment @kim0! It's interesting to see that you're struggling with more or less the same questions as Edward. Some examples, like the monitor.py should indeed probably be improved to make them more clear and promote good practice. I will put this in the todo the list too :)

**Comment by almarklein** [comment]
To answer your first question: you probably only need PyComponent and JsComponent with Flexx. The base Component class is a base class. Outside of making a Flexx app, the Component class could be used to make Components in Python-only applications.
