### ISSUE TITLE
How to style text in a flx.Button?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#572]
Hi,

Is it possible to set position _(top, left)_ of text in a button?
display _newline_'s in the buttons or at least word-wrap the text?

I tried with adding breaks (``<br />``) in the text and adding ``word-wrap: break-work;``, but those two things don't do anything.

I'm using __Flexx 0.8.0__ with __Python 3.7.2__.

Any ideas?
Thanks

**Comment by almarklein** [comment]
Mmm, it seems that `word-wrap: break-word;` does not work inside buttons. The `<br>` does not work because the given text does not accept html (it uses `innerText` not `innerHTML`).

It looks like you may need to create your own button, either by subclassing a button and adding an `html` propery like `flx.Label` has, or by going from scratch using a div and using CSS to style it like a button ...

**Comment by matkuki** [comment]
Ok, thanks👍

**Comment by matkuki** [comment]
@almarklein 
I tried subclassing a `Button` and adding the `html` property and `set_html` method like the `Label` has,
but that does not seem to display special characters. For example, a html string `MY<br/>TEXT` is displayed as `MYTEXT`?

**Comment by almarklein** [comment]
Mmm, that's odd. Does e.g. `My<b>TEXT</b>` work?

**Comment by matkuki** [comment]
No, it does not create bold text.
I just found a workaround by subclassing `flx.Button` and overriding it's `_render_dom` method with simply this:
```python
def _render_dom(self):
    super()._render_dom()
```
Then `set_html` copied from `flx.Label` starts working perfectly.
I noticed that `flx.Button`'s `_render_dom` just returns `[self.text]`, so that gave me the idea to try this.

Hope this helps.

**Comment by almarklein** [comment]
aah, that was the culprit then :)
