### ISSUE TITLE
Simple horizontally scrollable container?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#601]
Hi,

Is there a way to make a container, that is as wide as is the width of it's child widgets, horizontally scrollable?
I tried things like:
```python
with flx.Widget(style="width: 200px; height: 200px; overflow: auto;"):
  with flx.HBox(flex=1):
    for i in range(10):
      flx.Label(text="TEXTEXTEXTEYXTTEXETEXT", flex=1)
```
The above example does not work, but it illustrates my idea of putting as many children inside the `flx.HBox` as needed, which should make the horizontal scrollbar appear as soon as the width of the `flx.HBox` exceeds `200px;`.

Any ideas?

**Comment by gwingnhbc** [comment]
Hi,
I do something reasonably  similar although my outer container is a  VBox() rather than Widget() and it works for me.  As you ask for ideas I'd try putting the overflow on the HBox() itself rather than its parent but if for some reason that isn't suitable I'd try using  a more visible container than the simple Widget(),  or at least give that Widget() a flex value.
 
As another newcomer to Flexx  I do sometimes find it confusing to understand what  is happening with these layout objects so I like to initially set overflow:scroll rather than auto and also  put a border around the containers  so that I can actually see what is happening.
Rgds,
Rob.

**Comment by matkuki** [comment]
Hey @gwingnhbc 
Can you please give me a working example?
I tried this:
```python
from flexx import flx, ui, event, config

class Test(flx.Widget):
    def init(self):
        with flx.VBox(flex=1):
            with flx.HBox(flex=1, style="max-width: 50px; max-height: 50px; overflow: scroll;"):
                for i in range(10):
                    flx.Label(text="TEXTEXTEXTEYXTTEXETEXT", style="min-width: 200px;", flex=0)
test_app = flx.App(Test, title="TEST")
test_app.serve('')
flx.start()
```
... and it doesn't work.

Thanks

**Comment by gwingnhbc** [comment]
My attempts didn't work either, at least not as I think you probably want them to work.

There does seem a fundamental difference in how x and y overflows are treated. If we take the standard Flexx  'Scrollable.py' example and merely change 'overflow-y' to 'overflow-x'  we lose the scrolling and instead the layout dynamically changes in response to window resizing.

Altering the example 'Scrollable.py' further to use an HBox instead of Widget shows that the scrollbar is rendered but has no handles as the content does not need scrolling - instead the size of the widgets inside the containing HBox is reduced so that they fit without the need to scroll. If you now further reduce your window size to the point that the content widgets are forced smaller than their minimum size *then* they don't fit and then the scrollbars appear and the HBox is scrollable.

So a horizontally  scrolling HBox is possible, to get it working as I understand your needs I think we would need to get the widgets inside that HBox rendered at full size not truncated down to some dynamically calculated minimum . I'm not sure what the best way to do that would be.

**Comment by matkuki** [comment]
@almarklein 
Any guidelines on how to do this, even in some *hackish* way?

**Comment by matkuki** [comment]
Found that fixed width for the base container does the trick, like so:
```python
from flexx import flx, ui, event, config
        
class Test(flx.Widget):
    CSS = """
        .flx-Test {
            height: 500px;
            min-height: 500px;
            max-height: 500px;
            width: 500px;
            min-width: 500px;
            max-width: 500px;
            overflow: auto;
        }
    """
    def init(self):
        for n in ["ROW_" + str(x) for x in range(100)]:
            with flx.Widget(style="width: 100%; overflow: auto;") as line:
                with flx.HBox(style=f"border: 1px solid black; width: 1000px; min-width: 1000px;") as line:
                    checkbox = flx.CheckBox(
                        checked=False,
                        style="min-width: 40px;",
                        flex=0
                    )
                    flx.Label(
                        text = n,
                        style=f"""
                            background-color: grey;
                            border-radius: 4px;
                            min-width: 130px;
                            text-align: left;
                        """,
                        flex=0,
                    )
                    flx.Widget(flex=1)
        
test_app = flx.App(Test, title="TEST")
test_app.serve('')
flx.start()
```
