### ISSUE TITLE
How to create a new thread，please？

### ISSUE THREAD

**Issue by strsikin** [flexxui/flexx#605]
JS in "D:\asset\sys\lang\Python37\lib\subprocess.py" uses 'Popen' but cannot transpile it with PScript:

**Comment by almarklein** [comment]
Sorry, but I don't fully understand your question. Can you please be more specific? If you're asking to use the Python threading API in PScript, not going to happen, because JS does not work that way.

**Comment by strsikin** [comment]
i want to run flexx as app. that function is to create some process when button is pointed down。
so i use function [subprocess.Popen]. then got the error like this.

maybe i'm a new one to do right, but please teach me how to create process with button down?

**Comment by strsikin** [comment]
> Sorry, but I don't fully understand your question. Can you please be more specific? If you're asking to use the Python threading API in PScript, not going to happen, because JS does not work that way.

i want to run flexx as app. that function is to create some process when button is pointed down。
so i use function [subprocess.Popen]. then got the error like this.

maybe i'm a too new one to do right, but please teach me how to create process when button down?

**Comment by gwingnhbc** [comment]
Hi,
I have found no problem using Popen in flexx but it must execute in the Python code not javascript.  I do this to run sql processes on the server and to do this my structure is essentially:
1) Implement my flexx app as a PyComponent.
2) Create a root.store.doSQL component that just holds a dictionary of the runtime parameters my sql needs to know.  Create a flexx.reaction on this so that when the doSQL dictionary changes it calls a generic python function that runs sql with its runtime parameters. This reaction and the function it calls will run server side in python and therefore can contain popen calls.
3) On the button itself (which will execute client side in javascript) create a flexx reaction for 'pointer_click' which updates root.store.doSQL with the sql I want to run.

So the runtime process is user clicks button, which reacts to the click by updating the root data store, which reacts to the update by  running my  doSQL function (which contains the popen call or any other python specific  functions you need to run.

**Comment by strsikin** [comment]
> Hi,
> I have found no problem using Popen in flexx but it must execute in the Python code not javascript. I do this to run sql processes on the server and to do this my structure is essentially:
> 
> 1. Implement my flexx app as a PyComponent.
> 2. Create a root.store.doSQL component that just holds a dictionary of the runtime parameters my sql needs to know.  Create a flexx.reaction on this so that when the doSQL dictionary changes it calls a generic python function that runs sql with its runtime parameters. This reaction and the function it calls will run server side in python and therefore can contain popen calls.
> 3. On the button itself (which will execute client side in javascript) create a flexx reaction for 'pointer_click' which updates root.store.doSQL with the sql I want to run.
> 
> So the runtime process is user clicks button, which reacts to the click by updating the root data store, which reacts to the update by running my doSQL function (which contains the popen call or any other python specific functions you need to run.
> 
> I found the 'sensible usage patterns' section of the flexx documentation very helpful when first trying to understand this process.

oh，yes，you are right. There is no error about popen when to implement my flexx app as a PyComponent.
but I use "self.parent.parent.parent.function" in a flexx reaction when implementing my flexx app as a Widget. Now how could I do to be able to call function that exist in its parent Component?
Thank you for reply me so carefully and patiently. I'm willing to learn more knowledge and solutions from you.

**Comment by gwingnhbc** [comment]
If you have a child widget that is executing in javascript on the client it cannot directly call a python function on the server side, especially if that function (such as popen) has to be executed in real python not pscript transpiled to javascript.


What the child js code can do however is to update a property on a python/server side object as these properties are proxied by flexx between server and client. You can then have a reaction defined on that python side property calling the python function you wish to execute.  Like yourself I am a newcomer to flexx and finding my way so there may be better ways to do things than my suggestions, what I have found helpful is to follow the recommendations on using a 'central data store' in the 'sensible usage patterns' section of the flexx user guide as these can be easily referenced as root.store.object_name.
