### ISSUE TITLE
Direct access to JS methods from Python?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#640]
Hi,

I have a `JS widget` (a `Tabulator` table) wrapped in a `flx.Widget` (called `WrappedTabulator`), accessing the JS widget as an attribute `self.tabulator`.
This works great, except that I don't know of a way to access a `JS` method from a parent of `WrappedTabulator` directly. For example, I wish to call the `getRows()` method of `Tabulator` directly:
```python
# 'get_file_content' just reads a binary file
flx.assets.associate_asset(__name__, "tabulator.js", get_file_content("tabulator/js/tabulator.js"))
flx.assets.associate_asset(__name__, "tabulator.css", get_file_content("tabulator/css/tabulator.css"))

class WrappedTabulator(flx.Widget):
  def init(self):
    global Tabulator
    self.tabulator = Tabulator(...)

  def getRows(self):
    return self.tabulator.getRows() # <--- This doesn't work!

class MyWidget(flx.PyWidget):
  def init(self):
    self.wt = WrappedTabulator()
    rows = self.wt.getRows()
```
How do I get the `WrappedTabulator`'s `getRows` method to work?
Can this be done directly, without a `call action >> wait for emitter` workaround?

Thanks

**Comment by matkuki** [comment]
If anyone has an idea of how to do this, even in a hacky way, please let me know.

**Comment by almarklein** [comment]
I think the "This doesn't work!" comment should be at the line where you call `self.wt.getRows()` from the pywidget :)

Code in a pywidget run in Python, so you can only call js methods of `wt` via actions. So yeah, you'd probably need to send an event from `wt` that you then catch in the pywidget.

Event better would be if you can register an event in `Tabulator` for its number of rows, so that the wrapper can report back to the pywidget, so that it always has the correct number of rows ...
