### ISSUE TITLE
Long running application memory usage?

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#691]
Hi,

I have an server application with several `flexx` container `Pywidgets` with each having lots of child widgets.
The application create/destroys some widgets on the fly and that works great.
But after a user connects to the application, does some stuff, then exits the application (closes browser),
the memory usage of the application always gets a bit higher. As a reference, connecting to the application
that was freshly started doing something in the application, then exiting by closing the browser, puts memory
usage to about 250MB. After a couple of weeks of execution with an average of two-three connections per day,
the memory usage grew to 4900MB.
I am cleaning a few dynamic widgets manually with `dispose()`, but that doesn't seem to be enough.

Is there a way to clean all of the memory when a user disconnects or some other method of clearing up the memory
of a log running application?

Thanks

**Comment by almarklein** [comment]
I've seen this too in long-running applications. I haven't found the courage (and time) to dive into the cause though ...

Since I'm running it as a Docker container, I just set it up so the container will be closed (and then restarted) once it consumes a certain amount of memory. Another solution is to restart the application at a fixed interval. I know that these are not real solutions, though ...

**Comment by matkuki** [comment]
> I've seen this too in long-running applications. I haven't found the courage (and time) to dive into the cause though ...

Good to know, thanks.

Good idea for the restart workaround. Shouldn't be a problem as the application is used during the day.
Thanks again.
